controller_list:
  - name: fake_polar_arm_controller
    type: $(arg execution_type)
    joints:
      - polar_joint1
      - polar_joint2
      - polar_joint3
      - polar_joint4
      - polar_joint5
      - polar_joint6
initial:  # Define initial robot poses.
  - group: polar_arm
    pose: home