#polar:                    
    #useful if you use a namespace for the robot
    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    polar_arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - polar_joint1
            - polar_joint2
            - polar_joint3
            - polar_joint4
            - polar_joint5
            - polar_joint6

        constraints:
            goal_time: 2.0

        state_publish_rate: 100

    polar_hand_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            polar_hand_joint1
            # - polar_hand_joint1
            # - polar_hand_joint2
            # - polar_finger_joint1
            # - polar_finger_joint2

        state_publish_rate: 25